version: "3.8"
services:
  uksivtbot:
    image: arnew7/uksivtbotrust:v3_test
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - db_data:/Users/arnew/UKSIVTbot
      - /usr/share/zoneinfo/Asia:/usr/share/zoneinfo/Asia:ro
    depends_on:

      memcached:
        condition: service_healthy
    networks:
      - app-net

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep memcached || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-net


volumes:
  db_data:

networks:
  app-net:
    driver: bridge